name: 'action-store-release'
description: 'Internal action to send release notes to store'
inputs:
  strip_first_lines:  # id of input
    description: 'How many lines should strip from notes'
    required: false
    default: '4'
  no_notes:  # id of input
    description: 'Should we parse the commit message?'
    required: false
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'