on: [ push ]

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Sample job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        if: ${{ env.ACT }}
        with:
          path: "action-store-release"
      - name: Testing
        uses: ./
        if: ${{ env.ACT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}