on: [ push ]

jobs:
  pr_announcer:
    runs-on: ubuntu-latest
    name: Sample job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        if: ${{ env.ACT }}
        with:
          path: "action-pr-merged-announcer"
      - name: Checking merged commit
        uses: ./
        if: ${{ env.ACT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        with:
          destination_repo: "Codeinwp/docs"
          issue_labels: "neve"